import { StyleSheet,Dimensions } from "react-native";
let screenWidth=Dimensions.get('window').width;
let screenHeight=Dimensions.get('window').height;
const styles=StyleSheet.create({
    container:{
        backgroundColor:"white",
        width:screenWidth,
        height:screenHeight,
        paddingLeft:10,
        paddingRight:10,
        paddingBottom:10,
    },
    home:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        paddingTop:10,
        backgroundColor:'red',
    },
    header:{
        flexDirection:'row',
        alignItems:'center',
        marginTop:20,
        borderColor:'grey',
    },
    footer:{
        flexDirection:'row',
    },
    itemFooter:{
        marginLeft:32,
        justifyContent:'center',
        alignItems:'center',
    },
    logoutButton:{
        backgroundColor:"red",
        flexDirection:'row',
        paddingLeft:10,
        paddingLeft:20,
        paddingBottom:10,
        borderColor:'grey',
    },
    logoutText:{
        fontSize:20,
        marginLeft:10,
        color:'white',
    },
    iconLogout:{
        width:20,
        height:20,
    },
    imageHome:{
        width:screenWidth,
        height:screenHeight,
    },
    iconFooter:{
        width:30,
        height:30,
    },
    itemSidebar:{
        flexDirection:'row',
        marginBottom:20,
        paddingLeft:20,
    },
    iconSidebar:{
        width:25,
        height:25,
    },
    textSidebar:{
        fontSize:16,
        marginLeft:20,
        color:'grey'
    },
    itemLogout:{
        flexDirection:'row',
        backgroundColor:'red',
        height:50,
        paddingTop:13,
        paddingBottom:10,
        width:'auto',
        paddingLeft:20,
    },
    textLogout:{
        color:'white',
        fontSize:16,
        marginLeft:20,
    },
    profileContainer:{
        width:screenWidth,
        height:screenHeight,
        paddingTop:20,
        paddingLeft:30,
        paddingRight:30,
        backgroundColor:'yellow'
    },
    itemProfile:{
        flexDirection:'row',
        borderBottomWidth:1,
        borderColor:'grey',
        borderTopWidth:1,
        borderLeftWidth:1,
        borderRightWidth:1,
        borderRadius:5,
        height:40,
        width:'auto',
        marginBottom:20,
        paddingRight:10,
        paddingTop:8,
        backgroundColor:'white',
        paddingLeft:10,
    },
    titleProfile:{
        color:'grey',
        fontSize:16,
        width:80,
    },
    itemContent:{
        fontSize:16,
        color:"black",
        marginLeft:20,
        fontWeight:'bold',
    },
    imageMenu:{
        width:30,
        height:30,
        alignSelf:'flex-start',
    },
    backgroundHome:{
        width:screenWidth,
        height:520,
        paddingRight:10,
        paddingBottom:30,
        marginTop:20,
        justifyContent:'center',
        alignItems:'center'
    },
    textMenu:{
        fontSize:20,
        marginLeft:120,
    }
});
export default styles;